import re

path = 'src/components/CourseDetailModal.tsx'
with open(path, 'r', encoding='utf8') as f:
    content = f.read()

content = content.replace("פתח ב-SAP ↗", "{t('openInSap')}")
content = content.replace("נספר לשרשראות:", "{t('countedForChains')}")
content = content.replace("קורס זה נספר כליבה. הקצאה לשרשרת תשחרר אותו מספירת הליבה.", "{t('countedAsCoreHint')}")
content = content.replace("{role === 'mandatory' ? 'חובה' : 'בחירה'}", "{role === 'mandatory' ? t('mandatory') : t('elective')}")
content = content.replace("✓ מוקצה", "{t('assigned')}")
content = content.replace('title="הקצה קורס זה לשרשרת זו בלבד"', 'title={t("assignToThisChainOnly")}')
content = content.replace(">הקצה<", ">{t('assignBtn')}<")
content = content.replace("הקורס נספר רק בשרשרת המוקצית", "{t('countedOnlyInAssigned')}")
content = content.replace("החזר לליבה", "{t('returnToCore')}")
content = content.replace(">תנאי קדם<", ">{t('prerequisitesTitle')}<")
content = content.replace("אין תנאי קדם", "{t('noPrerequisites')}")
content = content.replace("תנאי קדם <span", "{t('prerequisitesTitle')} <span")
content = content.replace("— מוחלף ע״י {subTargetCourse.name}", "— {t('replacedBy')} {subTargetCourse.name}")
content = content.replace("תנאי קדם{' '}", "{t('prerequisitesTitle')}{' '}")
content = content.replace("`מוחלף ע״י ${subTargetCourse.name}`", "` ${t('replacedBy')} ${subTargetCourse.name}`")
content = content.replace("'אוטומטי'", "t('auto')")
content = content.replace("'הרכב מותאם'", "t('customComposition')")
content = content.replace("`אפשרות ${mode + 1} נבחרה`", "t('optionSelected').replace('{n}', (mode + 1).toString())")
content = content.replace('אוטומטי <span className="text-gray-400 font-normal">(ברירת מחדל)</span>', "{t('auto')} <span className=\"text-gray-400 font-normal\">({t('autoDefault').split('(')[1]}")
content = content.replace("אפשרות {gi + 1}", "{t('optionN').replace('{n}', (gi + 1).toString())}")
content = content.replace("הרכב קדמים בעצמי...", "{t('customPrereqComposition')}")
content = content.replace('placeholder="חפש קורס להוספה..."', 'placeholder={t("searchCourseToAdd")}')
content = content.replace(">מחליף קדם<", ">{t('prereqReplacement')}<")
content = content.replace("אם קורס זה שקול לקורס אחר בטכניון, בחר אותו כדי שיתפוס את מקומו בבדיקת קדמים.", "{t('prereqReplacementHint')}")
content = content.replace('placeholder="חפש קורס לפי שם או מספר..."', 'placeholder={t("searchCourseByNameOrId")}')
content = content.replace(">מה תלוי בקורס זה<", ">{t('whatDependsOnThis')}<")
content = content.replace("אין קורסים שתלויים בקורס זה", "{t('noDependentCourses')}")
content = content.replace("{downstreamTotal} קורסים תלויים בקורס זה", "{downstreamTotal} {t('dependentCoursesCount')}")
content = content.replace("✓ בתכנית", "{t('inPlan')}")
content = content.replace(">ללא זיכוי נוסף<", ">{t('noAdditionalCreditTitle')}<")
content = content.replace("הקורס מתנגש בזיכוי עם {otherName}.", "{t('creditConflictWith')} {otherName}.")
content = content.replace("קורס זה ללא זיכוי", "{t('thisCourseNoCredit')}")
content = content.replace("הקורס השני ללא זיכוי", "{t('otherCourseNoCredit')}")
content = content.replace("ברירת המחדל היא שהקורס המאוחר יותר בתוכנית לא יקבל נק\"ז.", "{t('noCreditDefaultHint')}")
content = content.replace(">קורס מכיל<", ">{t('containingCourseTitle')}<")
content = content.replace("קורס זה מכיל את {courses.get(containingSubstitution.containedCourseId)?.name ?? containingSubstitution.containedCourseId} (קורס חובה).{' '}", "{t('containsCourse')} {courses.get(containingSubstitution.containedCourseId)?.name ?? containingSubstitution.containedCourseId} ({t('mandatory')}).{' '}")
content = content.replace("{containingSubstitution.mandatoryCredits} נק\"ז נספרות כחובה במקומו", "{containingSubstitution.mandatoryCredits} {t('mandatoryCreditsCounted')}")
content = content.replace(", והיתרה ({containingSubstitution.excessCredits} נק\"ז) נספרת כבחירה חופשית.", "{t('excessCreditsCounted').replace('{credits}', containingSubstitution.excessCredits.toString())}")

with open(path, 'w', encoding='utf8') as f:
    f.write(content)
